### ISSUE TITLE
Winpcap package problem

### ISSUE THREAD

**Issue by jgruszka93** [streanger/clients-scanner#1]
After installing with `pip install clients_scanner` and launching via
```
from clients_scanner import scanner
scanner()
```

I've got:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\...\clients_scanner\clients_scanner.py", line 323, in search_clients_thread
    clients = self.get_clients(target_ip=self.target_ip, iterations=1)
  File "C:\Users\...\clients_scanner\clients_scanner.py", line 374, in get_clients
    result = srp(packet, timeout=1.0, verbose=0)[0]
  File "C:\Users\...\venv\lib\site-packages\scapy\sendrecv.py", line 503, in srp
    s = conf.L2socket(promisc=promisc, iface=iface,
  File "C:\Users\...\venv\lib\site-packages\scapy\arch\windows\__init__.py", line 1068, in __init__
    raise RuntimeError(
RuntimeError: Sniffing and sending packets is not available at layer 2: winpcap is not installed. You may use conf.L3socket orconf.L3socket6 to access layer 3
```

**Comment by Thioby** [comment]
You have to install `winpcap` manually.

**Comment by jgruszka93** [comment]
> You have to install `winpcap` manually.

@Thioby  Thanks for your answer. I'll check it. 
However I think it should be mentioned in readme - what do you think @streanger ?

**Comment by streanger** [comment]
@jgruszka93 I made few changes and included info about Winpcap/Npcap install: https://github.com/streanger/clients-scanner/commit/91f3835c09dc38bef3479418b72bda24fad936aa
